language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
deploy:
  provider: s3
  access_key_id:
    secure: iEs/bvpMOC42jql2OGKLclbDSD3wzPVMMemTnTlKwxfkj8DmeBY97n80zOmxEuDBG/D6MpTMWVnOYucbKNaTV/XxH8gEbvO6rg6CMUBz8Z1p/41exKCyTypvIs3xi07l3LUOzPkR/cuDoNlTrWTCs9+IXdRBL8yLoe8pburhFf685oUN3kcWMda4UoMOFoGOLUW6ZVDhI5NT6Nndf0CfNgG41RIaEm2F0Ls/h+jw+tv0RSkHtUPpc7tIyL4tw55S9hTzUBuPXGyYKPift3jr9x7UqkndvroLWhEIcjjxLByj96g6dyonHmVjoHSsw2HCf1us9HVinbUft4GCpzaEg90AzfS4xEinVeE9hbCE2FcJV6G503D6BGK8FP58qWbQ7V/5/XhVU3VEHOJzwccG/iFHlIfBqkkWHyF9kWJOxZSTZWToWpCzr6LhQe5KQ+fEa6n02N4TXFb4nx+TMR0zwoOrRH6EHqRDn+20E5ve8/tdLEz+bN7FXWEltCb9Dhtwz7i5xaozVmjcSlxEHnqiW9p1RXhbIYR7g7pGxVayxPrGaI6AwVdbWALVkVqOqkHPtsXInlxET6mJqxxzk+bgIyAxzPvjWNNeE45adbwp4ImIgJTiRBWdIVXCHhqvFRNc0aNtAFpgxDCYcrrjLhLBIgSPwu9A+2DUuEima+zWH6Q=
  secret_access_key:
    secure: Pkq2umGcUvJIepOtoIMtDp3PYw8jbeKyKbWBxJjQ05KBRTY6qcUW/qo2brcSUacDsOf+ZMymknszzanMoUK4C7rilQc3zy6aaIp7WCaobMi4qvdGrlOaGBVdHL+253hFWvjnkfwaZ8VGHgl/ZkeKQ7ZIPu1EUIycT1U09mjb1+5bmkc2WXDnr01zmfKfNeTv5t7JSwUz3NJiKZH0eKFl8TQKIiJwiIGAIcYGSnFOsEu7tlGLGM/U24jfMnJrtuiziEtDYyVSIpv46OKhekLVGWs8/iF/XpeEe2Wc/qNO9FEZzGd2RSsjuI5rq+H6ai/8kaE9l7CSDAPKUUWV1rjVgtTHyabD/3t0SYuN3cHI95IWvqS6m0bxAeLU1XXrBzpaF60nVGezJuAmR2FQLfVoYP3AWA4SFDvwKZATc8EnkLYWFt+RIVPtlqSUpuE1W7DHWBVgWZscEkOoXpADjrGb9fsLsK5qkYD7KZYmbbVpuNXSe1CFZrcKwmUBHoUuvYK148Lt0PZH2GbEtLCPl6qPZ7LTIe+0+lzo43XmtGZfvIHhdbcqcbwHGSwzhSeqLkny8hKBZY7s16dKxUPjMHRb+B2Pl2UGKMqza3hesGU6n6SHhtjLhSyzG1M1TMMfn4R/pRWzEB4wXevGtx9vHj/z7p1Kz7+8JZLHHcYH1kwZRds=
  bucket: powerbrahl.bucket
  skip_cleanup: true
  region: us-west-1
  acl: public-read
  on:
    repo: michaeldahl7/PowerBrahl
